export interface ProcessoSeletivoInscricao {
  uuid: string;
  numeroInscricao?: number;
  status?: string;
  nome: string;
  cpf: string;
  email: string;
  dataNascimento?: string;
  estadoCivil?: string;
  nacionalidade?: string;
  paisOrigem?: string;
  campoAtuacao?: string;
  telefone?: string;
  cep?: string;
  endereco?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  cidade?: string;
  uf?: string;
  pcd?: boolean;
  descricaoPcd?: string;
  afrodescendente?: boolean;
  escolaridade?: string;
  cursoFormacao?: string;
  instituicaoEnsino?: string;
  anoConclusao?: string;
  possuiExperiencia?: boolean;
  experienciaCargo?: string;
  experienciaEmpresa?: string;
  experienciaInicio?: string;
  experienciaFim?: string;
  experienciaDescricao?: string;
}

export interface ProcessoSeletivoInscricaoPayload {
  nome: string;
  cpf: string;
  email: string;
  dataNascimento?: string;
  estadoCivil?: string;
  nacionalidade?: string;
  paisOrigem?: string;
  campoAtuacao?: string;
  telefone?: string;
  cep?: string;
  endereco?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  cidade?: string;
  uf?: string;
  pcd?: boolean;
  descricaoPcd?: string;
  afrodescendente?: boolean;
  escolaridade?: string;
  cursoFormacao?: string;
  instituicaoEnsino?: string;
  anoConclusao?: string;
  possuiExperiencia?: boolean;
  experienciaCargo?: string;
  experienciaEmpresa?: string;
  experienciaInicio?: string;
  experienciaFim?: string;
  experienciaDescricao?: string;
  documentoRgCnh?: File | null;
  comprovanteResidencia?: File | null;
  comprovanteEscolaridade?: File | null;
  laudoMedicoPcd?: File | null;
  tbprocessoSeletivoId?: number;
}
